# sample docker compose file
version: '2'
services:
  web:
    build: .
    ports:
      - "1212:1212"
    links:
      - postgres
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    environment:
      # dsn remote connection url
      SQL_DSN: "user=admin password=password dbname=gochat host=postgres port=5432"

  postgres:
    image: "postgres"
    volumes:
    - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "gochat"
